import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/adminGuard";
import { prisma } from "@/lib/db";
import { hashPassword, verifyPassword } from "@/lib/password";
import { adminProfileSchema, changePasswordSchema, createAdminSchema } from "@/lib/validation";
export const dynamic = "force-dynamic";
export async function GET() { const g = await requireAdmin(); if (!g.ok) return g.response; const [currentAdmin, admins] = await Promise.all([prisma.admin.findUnique({ where: { id: g.session.sub }, select: { id: true, fullName: true, email: true, role: true } }), prisma.admin.findMany({ select: { id: true, fullName: true, email: true, role: true, status: true, createdAt: true }, orderBy: { createdAt: "asc" } })]); return NextResponse.json({ currentAdmin, admins }); }
export async function PATCH(req: Request) { const g = await requireAdmin(); if (!g.ok) return g.response; const body = await req.json().catch(() => null) as { action?: string } & Record<string, unknown> | null; if (body?.action === "profile") { const p = adminProfileSchema.safeParse(body); if (!p.success) return NextResponse.json({ error: "Enter a valid name and email" }, { status: 400 }); const exists = await prisma.admin.findFirst({ where: { email: p.data.email, NOT: { id: g.session.sub } } }); if (exists) return NextResponse.json({ error: "That email is already in use" }, { status: 409 }); const admin = await prisma.admin.update({ where: { id: g.session.sub }, data: p.data, select: { id: true, fullName: true, email: true } }); return NextResponse.json({ admin }); } if (body?.action === "password") { const p = changePasswordSchema.safeParse(body); if (!p.success) return NextResponse.json({ error: "Use a new password of at least 8 characters" }, { status: 400 }); const admin = await prisma.admin.findUnique({ where: { id: g.session.sub } }); if (!admin || !(await verifyPassword(p.data.currentPassword, admin.passwordHash))) return NextResponse.json({ error: "Current password is incorrect" }, { status: 400 }); await prisma.admin.update({ where: { id: admin.id }, data: { passwordHash: await hashPassword(p.data.newPassword) } }); return NextResponse.json({ ok: true }); } return NextResponse.json({ error: "Unknown action" }, { status: 400 }); }
export async function POST(req: Request) { const g = await requireAdmin(); if (!g.ok) return g.response; const p = createAdminSchema.safeParse(await req.json().catch(() => null)); if (!p.success) return NextResponse.json({ error: "Enter a name, valid email, and password of at least 8 characters" }, { status: 400 }); if (await prisma.admin.findUnique({ where: { email: p.data.email } })) return NextResponse.json({ error: "That email is already in use" }, { status: 409 }); const admin = await prisma.admin.create({ data: { fullName: p.data.fullName, email: p.data.email, passwordHash: await hashPassword(p.data.password) }, select: { id: true, fullName: true, email: true, role: true, status: true, createdAt: true } }); return NextResponse.json({ admin }, { status: 201 }); }
